name: ci

on:
  push:
    branches:
      - main
      - release*
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - release*

permissions:
  contents: read

env:
  GO_VERSION: "^1.21"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: vet
      run: go vet ./...
    - name: setup-dependencies
      run: ASSETS_DIR="./assets/" make setup-dependencies
    - name: lint
      run: ASSETS_DIR="./assets/" make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: vet
      run: go vet ./...
    - name: make-test
      run: make test
